// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ID struct {
	ID string `json:"id"`
}

type IDInput struct {
	ID string `json:"id"`
}

type NewUser struct {
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
}

type OldUser struct {
	ID        string `json:"id"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
}

type Status struct {
	Status int `json:"status"`
}

type User struct {
	ID        string `json:"id"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
}
